### ISSUE TITLE
Can't find executable?

### ISSUE THREAD

**Issue by randylewis7** [zsims/hunt-and-peck#12]
Excuse me if I'm missing something obvious, but I can't figure out how to run this. I have downloaded and unzipped the folder. I looked everywhere through it, but can't find an executable file. Inside src/HuntAndPeck, I found several files named "App", with the following types: xml configuration file, windows markup file, visual C# source file. Additionally, only level up, in src, I found HuntAndPeck, a microsoft visual studio file. But I can't figure out how to run the darn thing. I tried from the file explorer, and from the command line (speaking of which, did you mean to write "app.exe", not "hap.exe"?)

Excited to try out your software!

Thanks

**Comment by zsims** [comment]
You'll need to download a zip of one of the builds (as mentioned in the README), e.g. https://ci.appveyor.com/project/zsims/hunt-and-peck/build/artifacts

Thanks for giving it a whirl! Still a biy rough in some areas, but the idea is fun to play with :)

**Comment by randylewis7** [comment]
Awesome, that worked, thanks! Didn't realize I wasn't downloading the built version, sorry.

**Comment by zsims** [comment]
No stress, thanks for giving it a whirl 😁

**Comment by bradeac** [comment]
The artifacts got deleted (older than 6 months). 

Can you queue a new build please ?

Thanks

**Comment by leadbro** [comment]
HI!
Same issue: the artifacts got deleted (older than 6 months). Can you queue a new build please?
Thanks.

**Comment by Vijaynrt851** [comment]
Can you provide the steps for downloading the exe and run it
