### ISSUE TITLE
Can't get overlay window to come up?

### ISSUE THREAD

**Issue by randylewis7** [zsims/hunt-and-peck#13]
Hello, again I apologize if I am missing something obvious, but I can't get this to do anything. I am running the executable on windows 7. It's definitely running--I can see it in the taskbar. But pressing alt + doesn't bring up any overlay window. Am I getting the shortcut right? I am pressing the alt key and the +/= key at the same time. I tried both alt keys, and various cominations with ctrl and shift as well. Alt by itself brings up some vim like prompts in a few Microsoft programs, but I'm pretty sure this is built into the program.

I have tried this in microsoft word, paint, google chrome, the file browser, and netbeans. I also switched the mode back and forth between overlay and keyboard, which doesn't change anything.

Thanks again!

**Comment by zsims** [comment]
Try `Alt` and `;`

**Comment by randylewis7** [comment]
That worked, thanks! And this looks like exactly what I was looking for. Good job!

**Comment by zsims** [comment]
Cheers! Not every program implements the UI automation patterns correctly. The API can also be very slow. Let me know how you go!

**Comment by randylewis7** [comment]
Will do! I did notice it's slightly laggy, but not enough to be a big deal. Still much faster than the mouse.
