### ISSUE TITLE
confusing release 1.2

### ISSUE THREAD

**Issue by jmlucjav** [zsims/hunt-and-peck#17]
so, last was 1.4, and now there is a new one that is 1.2? Also I do not see any new commits barring to the readme?

thanks for clarifying

**Comment by zsims** [comment]
Sorry for the confusion. No new release, was just copying builds from CI as they expire every few months

**Comment by jmlucjav** [comment]
ok thanks! but...if I want to use the latest&greatest release so far, should I use 1.4 or this 1.2? sorry if i'b being obtuse

**Comment by zsims** [comment]
1.4 is latest. I have updated the readme. Sorry for the confusion

**Comment by jmlucjav** [comment]
np, thanks, I still use this daily!
