### ISSUE TITLE
Add support for focus hints

### ISSUE THREAD

**Issue by zsims** [zsims/hunt-and-peck#3]
Currently on Invoke hints are displayed, this means some elements can't be interacted with. Specifically giving focus to text boxes, which would be handy!

**Comment by extratype** [comment]
I found `IsKeyboardFocusable` useful but there're too much elements where `IsKeyboardFocusable` is `true`. Edit boxes usually support Value pattern so I made use of it. I also added more patterns that can be interacted like Invoke pattern. https://github.com/extratype/hunt-and-peck/blob/more-hints/src/hap/Services/UiAutomationHintProviderService.cs#L581

**Comment by zsims** [comment]
Hey! Thanks for looking into this. Did it help improve things much? If so, raise a PR and we can merge it :)

**Comment by zsims** [comment]
Happy that #9 addresses this
