### ISSUE TITLE
The hint Alt + doesn't work. 

### ISSUE THREAD

**Issue by vlad-terin** [zsims/hunt-and-peck#5]
I can't seem to install this application. 
I tried to run it on windows 10, 8, 7

All I see is windows related vim navigation. 
I have .net 4.5

http://prntscr.com/76tea1

**Comment by zsims** [comment]
Thanks for raising this. I'll look into it, sorry for the delay :smile:

**Comment by zsims** [comment]
Ok, should have fixed this with the latest release. Let me know how you go.
