### ISSUE TITLE
13.1 not working on most places anymore?

### ISSUE THREAD

**Issue by jmlucjav** [zsims/hunt-and-peck#6]
I just upgraded to 1.3.1 and I feel this works in less places than it worked before. One scenario I am sure of:

Using Git for Windows ui, I invoke it via autohotkey, and the hint show up, good. Would then, trying to close the main window for instance does nothing. This I am positive worked in 1.1.

Am I doing something wrong?
Also, what is the command like that shows at the bottom of most windows for? never found out...

thanks!

**Comment by zsims** [comment]
Thanks for raising this. Version 1.3 changed the way the automation API is queried to address some of the performance problems. It helped with performance, but obviously has regressed some areas.

I'll look into this soon, but in the meantime 1.2 should work for your case.

**Comment by jmlucjav** [comment]
just saw 1.4 is out, installed and this issue is fixed...I think it feels faster too?? sweet, thanks for the good job.

**Comment by zsims** [comment]
Great! Thanks for letting me know :)

**Comment by zsims** [comment]
And thanks to @extratype for adding the extra hint types
